export { Hero } from "./Hero"
export { default as Footer } from "./Footer/Footer"
export { default as Banner } from "./Banner/Banner"
export { default as Testimonials } from "./Testimonials/Testimonials"
export {  FeaturedTours } from "./FeaturedDestinations/FeaturedTours"
export { default as Trending } from "./Trending/Trending"
export { default as Card } from "./Card/Card"
