export { default as Header } from "./Header/Header"
export { default as Footer } from "./Footer/Footer"
export { default as Banner } from "./Banner/Banner"
export { default as Testimonials } from "./Testimonials/Testimonials"
export { default as FeaturedDestinations } from "./FeaturedDestinations/FeaturedDestinations"
export { default as Trending } from "./Trending/Trending"
export { default as Card } from "./Card/Card"
